<?php return array (
  'site_title' => 'SMM Matrix',
  'time_zone' => 'UTC',
  'base_color' => '#ff8503',
  'secondary_color' => '#ff8503',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'theme' => 'lightorange',
  'fraction_number' => 2,
  'paginate' => 20,
  'email_verification' => 0,
  'email_notification' => 0,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'sender_email' => 'support@domain.com',
  'sender_email_name' => 'Bug Finder',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'domain.com',
    'smtp_port' => '465',
    'smtp_encryption' => 'ssl',
    'smtp_username' => 'support@domain.com',
    'smtp_password' => '9c09270f5448ad',
  ),
  'push_notification' => 0,
  'deposit_commission' => 1,
  'is_active_cron_notification' => 1,
  'error_log' => 1,
  'maintenance' => 0,
  'maintenance_message' => 'Sorry for the inconvenience.<br />Our website is currently undergoing scheduled maintenance',
  'tawk_id' => '62d7e2fcb0d10b6f3e7d4766',
  'tawk_status' => 1,
  'fb_messenger_status' => 0,
  'fb_app_id' => '1983831301869331',
  'fb_page_id' => '1983831301869331',
  'reCaptcha_status_login' => 0,
  'reCaptcha_status_registration' => 0,
  'MEASUREMENT_ID' => 'G-TFQZ8YZ468',
  'analytic_status' => 0,
);